export enum TYPES {
    FIELD_SERVICE = "FIELD_SERVICE",
    GAME_SERVICE = "GAME_SERVICE",

    FIELD_REPOSITORY = "FIELD_REPOSITORY",
    GAME_REPOSITORY = "GAME_REPOSITORY",
    PLAYER_REPOSITORY = "PLAYER_REPOSITORY",
    UNIT_REPOSITORY = "UNIT_REPOSITORY",

    FIELD_JSON_MAPPER = "FIELD_JSON_MAPPER"
};